version: '1.0'
name: build-dist
displayName: build-dist
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - dev-cli-打包
    tags:
      prefix:
        - v
stages:
  - name: stage-3173e0fe
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor:
      - Geoffwo
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches: []
        notify: []
        strategy:
          retry: '0'
